#!/usr/bin/env node
/**
 * {{CONNECTOR_NAME}} — MCP stdio server.
 *
 * A pipe, not a server: it reads newline-delimited JSON-RPC from stdin, posts
 * each message to the HR leave system's /api/mcp endpoint, and writes the
 * reply to stdout. Every tool definition, permission check and query lives in
 * the Laravel app, so this file does not change when the toolset does — which
 * is why an installed bundle keeps working as tools are added server-side.
 *
 * Zero dependencies, by design. The bundle ships no node_modules and runs on
 * any Node 18+ with nothing to install and nothing to audit.
 *
 * Baked at build time: server URL, connector name, version. The API key is
 * NOT baked — it arrives via the MCPB_API_KEY environment variable, which the
 * client fills from the sensitive user_config field and keeps in the OS
 * keychain rather than in a file people forward to each other.
 *
 * Generated by the HR Leave Management System. Do not edit by hand.
 */

'use strict';

const SERVER_URL = process.env.MCPB_SERVER_URL || '{{SERVER_URL}}';
const API_KEY = process.env.MCPB_API_KEY || '';
const VERSION = '{{VERSION}}';
const TIMEOUT_MS = Number(process.env.MCPB_TIMEOUT_MS || 30000);

/**
 * stdout carries the protocol and nothing else — a stray console.log here
 * corrupts the stream and the client drops the connection with no useful
 * error. Diagnostics go to stderr, which clients surface as server logs.
 */
function logError(...args) {
  console.error('[{{CONNECTOR_NAME}}]', ...args);
}

function send(message) {
  process.stdout.write(JSON.stringify(message) + '\n');
}

function rpcError(id, code, message) {
  return { jsonrpc: '2.0', id: id === undefined ? null : id, error: { code, message } };
}

/**
 * Post one JSON-RPC message upstream and return the parsed reply, or null
 * when the server accepted a notification and sent no body.
 */
async function forward(message) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const response = await fetch(SERVER_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'X-API-Key': API_KEY,
        'User-Agent': `aiapleave-mcpb/${VERSION}`,
      },
      body: JSON.stringify(message),
      signal: controller.signal,
    });

    // 202 with an empty body is how the server acknowledges a notification.
    if (response.status === 202) return null;

    const text = await response.text();
    if (!text) return null;

    try {
      return JSON.parse(text);
    } catch {
      // An HTML error page from a proxy or a maintenance screen lands here.
      // Say which, rather than letting the client report "invalid JSON".
      throw new Error(
        `Server returned ${response.status} with a non-JSON body. ` +
        `Check that ${SERVER_URL} is reachable and that the app is not in maintenance mode.`
      );
    }
  } finally {
    clearTimeout(timer);
  }
}

async function handle(message) {
  const id = Array.isArray(message) ? null : message && message.id;
  const isNotification = !Array.isArray(message) && message && message.id === undefined;

  if (!API_KEY) {
    if (isNotification) return;
    send(rpcError(id, -32001,
      'No API key configured. Set the API key for this connection in your client, ' +
      'or generate one in the HR leave system under Settings → MCP Server.'));
    return;
  }

  try {
    const reply = await forward(message);
    if (reply !== null) send(reply);
  } catch (error) {
    if (isNotification) return;

    const reason = error && error.name === 'AbortError'
      ? `The server did not respond within ${TIMEOUT_MS}ms.`
      : (error && error.message) || String(error);

    logError(reason);
    send(rpcError(id, -32603, reason));
  }
}

/**
 * Messages are newline-delimited. Buffering matters: a large tools/list reply
 * or a slow pipe splits a single message across several 'data' events, and
 * parsing per-chunk would fail on exactly the biggest payloads.
 */
let buffer = '';

/** Promises for requests read but not yet answered. */
const inFlight = new Set();

function track(promise) {
  inFlight.add(promise);
  promise.finally(() => inFlight.delete(promise));
}

process.stdin.setEncoding('utf8');

process.stdin.on('data', (chunk) => {
  buffer += chunk;

  let newline;
  while ((newline = buffer.indexOf('\n')) !== -1) {
    const line = buffer.slice(0, newline).trim();
    buffer = buffer.slice(newline + 1);

    if (!line) continue;

    let message;
    try {
      message = JSON.parse(line);
    } catch {
      send(rpcError(null, -32700, 'Parse error: the client sent invalid JSON.'));
      continue;
    }

    // Deliberately not awaited: requests are independent and a slow report
    // should not hold up a ping behind it. JSON-RPC ids keep replies matched.
    // Tracked so shutdown can wait for them — see the 'end' handler.
    track(handle(message));
  }
});

/**
 * Exit only once in-flight work has been answered.
 *
 * stdin closing does not mean the requests already read from it are finished:
 * each one is a round trip to the server. Exiting immediately drops those
 * replies, which a client sees as a request that silently never returns.
 */
process.stdin.on('end', async () => {
  await Promise.allSettled(Array.from(inFlight));
  process.exit(0);
});

process.on('uncaughtException', (error) => {
  logError('Fatal:', error && error.stack ? error.stack : error);
  process.exit(1);
});
